# This workflow will update the `latest` tag with the latest release, whenever a new release is published

name: Update Latest Tag on Release

on:
  release:
    types: 
      - publish

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
  
    steps: 
      - name: Update latest tag
        uses: EndBug/latest-tag@latest
